[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jumpmetrics"
version = "0.1.0"
description = "A brief description of your package"
readme = "README.md"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.8"  # Add this line
dependencies = [  # Add your dependencies here
    "pip>=22.2",
    "pandas==2.0.*",
    "scipy==1.10.*",
    "matplotlib==3.7.*",
    "scikit-learn==1.3.*"
]

# Remove or comment out the following section if you're not using it
# [tool.setuptools.dynamic]
# dependencies = {file = ["env.yml"]}