name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: jumpmetrics
        environment-file: env.yaml
        python-version: 3.9
        auto-activate-base: false
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest